name: capi-kamaji-proxmox
version: 0.0.5
appVersion: 1.33.5
description: A Helm chart for deploying a Kamaji Tenant Cluster on Proxmox VE using Cluster API
  and Kamaji.
icon: https://raw.githubusercontent.com/clastix/cluster-api-kamaji-proxmox/master/assets/proxmox-icon.png
type: application
apiVersion: v2
maintainers:
  - name: Clastix Labs
    email: authors@clastix.labs
keywords:
  - kubernetes
  - helm
  - cluster-api
  - kamaji
  - proxmox
home: https://kamaji.clastix.io
sources:
  - https://github.com/clastix/cluster-api-kamaji-proxmox
annotations:
  artifacthub.io/links: |
    - name: Clastix Labs
      url: https://github.com/clastix
  artifacthub.io/operator: "true"
  artifacthub.io/operatorCapabilities: "Full Lifecycle"
  artifacthub.io/changes: |
    - kind: commit
      description: Initial commit.
