kind: Cluster
apiVersion: cluster.x-k8s.io/v1beta2
metadata:
  labels:
    #cluster.x-k8s.io/cluster-name: {{ include "cluster-api-kamaji-proxmox.cluster-name" . | quote }}
  name: {{ include "cluster-api-kamaji-proxmox.cluster-name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.cluster.clusterNetwork }}
  clusterNetwork:
    {{- if .Values.cluster.clusterNetwork.apiServerPort }}
    apiServerPort: {{ .apiServerPort | default 6443 }}
    {{- end }}
    {{- if .Values.cluster.clusterNetwork.pods }}
    {{- if .Values.cluster.clusterNetwork.pods.cidrBlocks }}
    pods:
      cidrBlocks:
        {{- range .Values.cluster.clusterNetwork.pods.cidrBlocks }}
        - {{ . | quote }}
        {{- end }}
    {{- end }}
    {{- end }}
    {{- if .Values.cluster.clusterNetwork.services }}
    {{- if .Values.cluster.clusterNetwork.services.cidrBlocks }}
    services:
      cidrBlocks:
        {{- range .Values.cluster.clusterNetwork.services.cidrBlocks }}
        - {{ . | quote }}
        {{- end }}
    {{- end }}
    {{- end }}
    {{- if .Values.cluster.clusterNetwork.serviceDomain }}
    serviceDomain: {{ .Values.cluster.clusterNetwork.serviceDomain | default "cluster.local" | quote }}
    {{- end }}
  {{- end }}
  controlPlaneRef:
    apiGroup: controlplane.cluster.x-k8s.io
    kind: KamajiControlPlane
    name: {{ include "cluster-api-kamaji-proxmox.cluster-name" . }}
  infrastructureRef:
    apiGroup: infrastructure.cluster.x-k8s.io
    kind: ProxmoxCluster
    name: {{ include "cluster-api-kamaji-proxmox.cluster-name" . }}