
{{- range .Values.customRessources }}
apiVersion: v1
kind: {{ .kind }}
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: {{ include "cluster-api-kamaji-proxmox.cluster-name" $ | quote }}
  name: {{ include "cluster-api-kamaji-proxmox.cluster-name" $ }}-ressources-{{ .name }}
  namespace: {{ $.Release.Namespace }}
data: |-
  {{- .data | nindent 2 }}
{{- end }}