{{- range .Values.nodePools }}
---
kind: MachineDeployment
apiVersion: cluster.x-k8s.io/v1beta2
metadata:
  {{- with .autoscaling }}
  {{- if .enabled }}
  annotations:
    cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: {{ .minSize | quote }}
    cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: {{ .maxSize | quote }}
  {{- end }}
  {{- end }}
  labels:
    {{- with .autoscaling }}
    {{- if .enabled }}
    {{- .labels | toYaml | nindent 4 }}
    {{- end }}
    {{- end }}
    cluster.x-k8s.io/cluster-name: {{ include "cluster-api-kamaji-proxmox.cluster-name" $ | quote }}
  name: {{ include "cluster-api-kamaji-proxmox.cluster-name" $ }}-{{ .name }}-md
  namespace: {{ $.Release.Namespace }}
spec:
  clusterName: {{ include "cluster-api-kamaji-proxmox.cluster-name" $ | quote }}
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: {{ include "cluster-api-kamaji-proxmox.cluster-name" $ | quote }}
  template:
    metadata:
      labels:
        {{- with .autoscaling }}
        {{- if .enabled }}
        {{- .labels | toYaml | nindent 8 }}
        {{- end }}
        {{- end }}
        cluster.x-k8s.io/cluster-name: {{ include "cluster-api-kamaji-proxmox.cluster-name" $ | quote }}
        node-role.kubernetes.io/node: ""
    spec:
      bootstrap:
        configRef:
          apiGroup: bootstrap.cluster.x-k8s.io
          kind: KubeadmConfigTemplate
          name: {{ include "cluster-api-kamaji-proxmox.cluster-name" $ }}-{{ .name }}-kubeadmconfig-{{ include "kubeadmConfigTemplateHash" (dict "nodePool" .) }}
      clusterName: {{ include "cluster-api-kamaji-proxmox.cluster-name" $ | quote }}
      infrastructureRef:
        apiGroup: infrastructure.cluster.x-k8s.io
        kind: ProxmoxMachineTemplate
        name: {{ include "cluster-api-kamaji-proxmox.cluster-name" $ }}-{{ .name }}-proxmox-machine-{{ include "ProxmoxMachineTemplateHash" (dict "nodePool" . "Global" $) }}
{{- end }}