{{- if .Values.cluster.useProxmoxClusterTemplateResource }}
kind: ProxmoxClusterTemplate
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: {{ include "cluster-api-kamaji-proxmox.cluster-name" . | quote }}
  name: {{ include "cluster-api-kamaji-proxmox.cluster-name" . }}-proxmox-cluster-{{ include "ProxmoxClusterTemplateHash" . }}
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
{{ include "ProxmoxClusterTemplateSpec" . | indent 6 }}
{{- end }}